<a href="https://colab.research.google.com/github/ishantmr/learning/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch Learning Sessions

In [3]:
import torch
print(torch.__version__)


2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not availablem using CPU.")

GPU is not availablem using CPU.


Creating a Tensor

In [ ]:
torch.empty(2,3)

tensor([[4.2669e-35, 4.3261e-41, 4.2669e-35],
        [4.3261e-41, 0.0000e+00, 0.0000e+00]])

In [ ]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
a = torch.ones(3,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.rand(2,6)

tensor([[0.0815, 0.8652, 0.3921, 0.6096, 0.4796, 0.6517],
        [0.9744, 0.9815, 0.1420, 0.8100, 0.1973, 0.4190]])

RAND will give different values every time, so we can use seed to fix the values even few days after (code sharing mein it also helps)

In [ ]:
torch.manual_seed(100)
torch.rand(2,6)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080, 0.1180, 0.1217, 0.7356]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,6)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080, 0.1180, 0.1217, 0.7356]])

Custome Tensor values

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

evenly spaced values

In [ ]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

Identity matrix, diagaonal values as 1

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Full matrix of 3,3 with values as 5

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Shape will give you size

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])

Create new tensor with shape like x

In [ ]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6066403867832102197, 3617580396591068721, 6501281658827847470]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

Now rand will not work with this because rand generates float values

In [ ]:
x.dtype

torch.int64

convert data type of a tensor

In [ ]:
torch.tensor([1.0,2.0], dtype=torch.int32)

tensor([1, 2], dtype=torch.int32)

In [ ]:
y = x.to(torch.float32)

In [ ]:
torch.rand_like(y)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

Mathematical Operations

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x + 2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
x - 2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [ ]:
x * 2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [ ]:
x / 3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

Integer division

In [ ]:
(x * 100)// 3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [ ]:
((x * 100)//3)%2

tensor([[1, 0, 0],
        [1, 0, 0]])

In [ ]:
x ** 2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])
tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])


In [ ]:
a + b
a - b
a * b
a / b
a ** b
a % b

tensor([[0.5277, 0.2472, 0.1394],
        [0.4235, 0.0169, 0.0056]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# absolute value - distnace from zero, non-negative

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.0, 3.1,-5.6])

In [ ]:
torch.round(d)

tensor([ 2.,  2.,  3., -6.])

In [ ]:
torch.ceil(d)

tensor([ 2.,  2.,  4., -5.])

In [ ]:
torch.floor(d)

In [60]:
# clamp is interesting, min se chote wale min and max se bade wale max ban jayenge
torch.clamp(d, min=2, max=3)

tensor([2., 2., 3., 2.])

Reduction Operations

In [12]:
e = torch.randint(size =(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 5., 3.],
        [2., 3., 4.]])

Full matrix sum

In [14]:
#full matrix sum
torch.sum(e)

tensor(20.)

In [15]:
#sum column wise
torch.sum(e, dim=0)

tensor([5., 8., 7.])

In [16]:
#sum row wise
torch.sum(e, dim=1)

tensor([11.,  9.])

In [17]:
torch.mean(e)

tensor(3.3333)

In [18]:
torch.mean(e, dim=0)

tensor([2.5000, 4.0000, 3.5000])

In [21]:
torch.median(e)
torch.max(e)
torch.min(e)
torch.std(e)
torch.prod(e) #product
torch.var(e) #variance
torch.argmax(e) #will tell you the position of the largest item
torch.argmin(e) #will tell you the position of the smallest item

tensor(3)

In [23]:
torch.argmax(e, dim=0) #will tell you the position of the largest item
torch.argmin(e, dim=1) #will tell you the position of the smallest item

tensor([0, 0])

Matrix Operations

In [26]:
f = torch.randint(size=(2,3), low=10, high=20)
g = torch.randint(size=(3,2), low=10, high=20)

In [27]:
f

tensor([[17, 16, 11],
        [11, 18, 13]])

In [28]:
g

tensor([[17, 10],
        [15, 12],
        [14, 12]])

In [29]:
#matrix multiplication
torch.matmul(f,g)

tensor([[683, 494],
        [639, 482]])

In [32]:
#dot product (1*3 + 2*4 = 11)
h = torch.tensor([1,2])
i = torch.tensor([3,4])
torch.dot(h, i)

tensor(11)

In [35]:
#transpose dim 0 with dim 1
torch.transpose(f, 0, 1)

tensor([[17, 11],
        [16, 18],
        [11, 13]])

In [37]:
#determinant (can be done for sq matrix only - For a 2x2 matrix, it's ad - bc)
j = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
torch.det(j)

tensor(160.)

In [38]:
#inverse - f⁻¹(x) - sq matrix only
torch.inverse(j)

tensor([[ 0.1000, -0.0750,  0.0250],
        [ 0.2000,  0.1000, -0.4500],
        [-0.1000,  0.0750,  0.2250]])

In [40]:
h > i
h < i
h == i
h != i
h >= i
h <= i

tensor([True, True])

In [41]:
torch.log(h)

tensor([0.0000, 0.6931])

In [42]:
#exponential
torch.exp(i)

tensor([20.0855, 54.5981])

In [43]:
torch.sqrt(i)

tensor([1.7321, 2.0000])

In [44]:
torch.sigmoid(i)

tensor([0.9526, 0.9820])

In [48]:
j

tensor([[9., 3., 5.],
        [0., 4., 8.],
        [4., 0., 4.]])

In [50]:
#softmax - only for float
torch.softmax(f)

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 * (Tensor input, name dim, *, torch.dtype dtype = None)


In [47]:
torch.relu(j)

tensor([[9., 3., 5.],
        [0., 4., 8.],
        [4., 0., 4.]])