<a href="https://colab.research.google.com/github/ishantmr/learning/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)


2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not availablem using CPU.")

GPU is not availablem using CPU.


Creating a Tensor

In [ ]:
torch.empty(2,3)

tensor([[4.2669e-35, 4.3261e-41, 4.2669e-35],
        [4.3261e-41, 0.0000e+00, 0.0000e+00]])

In [ ]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
a = torch.ones(3,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.rand(2,6)

tensor([[0.0815, 0.8652, 0.3921, 0.6096, 0.4796, 0.6517],
        [0.9744, 0.9815, 0.1420, 0.8100, 0.1973, 0.4190]])

RAND will give different values every time, so we can use seed to fix the values even few days after (code sharing mein it also helps)

In [ ]:
torch.manual_seed(100)
torch.rand(2,6)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080, 0.1180, 0.1217, 0.7356]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,6)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080, 0.1180, 0.1217, 0.7356]])

Custome Tensor values

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

evenly spaced values

In [ ]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

Identity matrix, diagaonal values as 1

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Full matrix of 3,3 with values as 5

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Shape will give you size

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])