<a href="https://colab.research.google.com/github/ishantmr/learning/blob/main/tensors_in_pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch Learning Sessions

In [1]:
import torch
print(torch.__version__)


2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not availablem using CPU.")

GPU is not availablem using CPU.


Creating a Tensor

In [3]:
torch.empty(2,3)

tensor([[2.6625e-44, 0.0000e+00, 3.6954e-25],
        [0.0000e+00, 1.5512e-42, 0.0000e+00]])

In [4]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
a = torch.ones(3,3)

In [6]:
type(a)

torch.Tensor

In [7]:
torch.rand(2,6)

tensor([[0.3449, 0.3583, 0.1768, 0.1008, 0.7113, 0.4316],
        [0.2134, 0.3837, 0.7950, 0.5632, 0.2298, 0.0137]])

RAND will give different values every time, so we can use seed to fix the values even few days after (code sharing mein it also helps)

In [8]:
torch.manual_seed(100)
torch.rand(2,6)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080, 0.1180, 0.1217, 0.7356]])

In [9]:
torch.manual_seed(100)
torch.rand(2,6)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080, 0.1180, 0.1217, 0.7356]])

Custome Tensor values

In [10]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

evenly spaced values

In [12]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

Identity matrix, diagaonal values as 1

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Full matrix of 3,3 with values as 5

In [14]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Shape will give you size

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])

Create new tensor with shape like x

In [16]:
torch.empty_like(x)

tensor([[135337151438224,       384110656,             464],
        [            112,       385671497,      4294967296]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

Now rand will not work with this because rand generates float values

In [19]:
x.dtype

torch.int64

convert data type of a tensor

In [20]:
torch.tensor([1.0,2.0], dtype=torch.int32)

tensor([1, 2], dtype=torch.int32)

In [21]:
y = x.to(torch.float32)

In [22]:
torch.rand_like(y)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [23]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

Mathematical Operations

In [24]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
x + 2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [26]:
x - 2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [27]:
x * 2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [28]:
x / 3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

Integer division

In [29]:
(x * 100)// 3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [30]:
((x * 100)//3)%2

tensor([[1, 0, 0],
        [1, 0, 0]])

In [31]:
x ** 2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])


In [33]:
a + b
a - b
a * b
a / b
a ** b
a % b

tensor([[0.4440, 0.2063, 0.7445],
        [0.0657, 0.0060, 0.0377]])

In [34]:
c = torch.tensor([1, -2, 3, -4])

In [35]:
# absolute value - distnace from zero, non-negative

In [36]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [37]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [38]:
d = torch.tensor([1.9, 2.0, 3.1,-5.6])

In [39]:
torch.round(d)

tensor([ 2.,  2.,  3., -6.])

In [40]:
torch.ceil(d)

tensor([ 2.,  2.,  4., -5.])

In [41]:
torch.floor(d)

tensor([ 1.,  2.,  3., -6.])

In [42]:
# clamp is interesting, min se chote wale min and max se bade wale max ban jayenge
torch.clamp(d, min=2, max=3)

tensor([2., 2., 3., 2.])

Reduction Operations

In [43]:
e = torch.randint(size =(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 9., 4.],
        [0., 5., 7.]])

Full matrix sum

In [44]:
#full matrix sum
torch.sum(e)

tensor(28.)

In [45]:
#sum column wise
torch.sum(e, dim=0)

tensor([ 3., 14., 11.])

In [46]:
#sum row wise
torch.sum(e, dim=1)

tensor([16., 12.])

In [47]:
torch.mean(e)

tensor(4.6667)

In [48]:
torch.mean(e, dim=0)

tensor([1.5000, 7.0000, 5.5000])

In [49]:
torch.median(e)
torch.max(e)
torch.min(e)
torch.std(e)
torch.prod(e) #product
torch.var(e) #variance
torch.argmax(e) #will tell you the position of the largest item
torch.argmin(e) #will tell you the position of the smallest item

tensor(3)

In [50]:
torch.argmax(e, dim=0) #will tell you the position of the largest item
torch.argmin(e, dim=1) #will tell you the position of the smallest item

tensor([0, 0])

Matrix Operations

In [51]:
f = torch.randint(size=(2,3), low=10, high=20)
g = torch.randint(size=(3,2), low=10, high=20)

In [52]:
f

tensor([[15, 19, 19],
        [17, 15, 19]])

In [53]:
g

tensor([[18, 19],
        [17, 19],
        [12, 16]])

In [54]:
#matrix multiplication
torch.matmul(f,g)

tensor([[821, 950],
        [789, 912]])

In [55]:
#dot product (1*3 + 2*4 = 11)
h = torch.tensor([1,2])
i = torch.tensor([3,4])
torch.dot(h, i)

tensor(11)

In [56]:
#transpose dim 0 with dim 1
torch.transpose(f, 0, 1)

tensor([[15, 17],
        [19, 15],
        [19, 19]])

In [57]:
#determinant (can be done for sq matrix only - For a 2x2 matrix, it's ad - bc)
j = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
torch.det(j)

tensor(-120.)

In [58]:
#inverse - f⁻¹(x) - sq matrix only
torch.inverse(j)

tensor([[ 4.1667e-02, -3.3333e-01,  3.4167e-01],
        [-4.1667e-02,  3.3333e-01, -1.4167e-01],
        [ 1.2500e-01,  7.4506e-09, -1.7500e-01]])

In [59]:
h > i
h < i
h == i
h != i
h >= i
h <= i

tensor([True, True])

In [60]:
torch.log(h)

tensor([0.0000, 0.6931])

In [61]:
#exponential
torch.exp(i)

tensor([20.0855, 54.5981])

In [62]:
torch.sqrt(i)

tensor([1.7321, 2.0000])

In [63]:
torch.sigmoid(i)

tensor([0.9526, 0.9820])

In [64]:
j

tensor([[7., 7., 8.],
        [3., 6., 1.],
        [5., 5., 0.]])

In [65]:
#softmax - only for float
torch.softmax(f)

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 * (Tensor input, name dim, *, torch.dtype dtype = None)


In [ ]:
torch.relu(j)

Inplace Operations

In [67]:
m = torch.rand(2,3)
n = torch.rand(2,3)

m + n #this is a new tensor and is stored as separate tensor in memory so memory wastage

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [68]:
#so we can add n to m and store it in m itself
m.add_(n)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [69]:
m

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [70]:
m.relu_() #this is permanent change in m (inplace changes)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [71]:
m


tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])