<a href="https://colab.research.google.com/github/ishantmr/learning/blob/main/tensors_in_pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Copying Tensors

In [10]:
import torch
import time

In [5]:
a = torch.rand(2,3)
a

tensor([[0.3610, 0.8243, 0.7308],
        [0.8075, 0.9083, 0.4117]])

In [6]:
b = a
b

tensor([[0.3610, 0.8243, 0.7308],
        [0.8075, 0.9083, 0.4117]])

In [7]:
a[0][0] = 22
a

tensor([[22.0000,  0.8243,  0.7308],
        [ 0.8075,  0.9083,  0.4117]])

In [8]:
b #b will also get updated

tensor([[22.0000,  0.8243,  0.7308],
        [ 0.8075,  0.9083,  0.4117]])

In [14]:
id(a)

138596478863504

In [15]:
id(b) #will be same

138596477465808

In [11]:
b = a.clone()
b

tensor([[22.0000,  0.8243,  0.7308],
        [ 0.8075,  0.9083,  0.4117]])

In [12]:
a[0][1] = 44
a

tensor([[22.0000, 44.0000,  0.7308],
        [ 0.8075,  0.9083,  0.4117]])

In [13]:
b #will not get updated now and will have different id now

tensor([[22.0000,  0.8243,  0.7308],
        [ 0.8075,  0.9083,  0.4117]])

GPU Operations

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device("cuda")

In [5]:
torch.rand((2,3), device=device)
#this will create a new tensor on new cuda device (gpu)

tensor([[0.7198, 0.0269, 0.8491],
        [0.2848, 0.6863, 0.3743]], device='cuda:0')

In [8]:
#move existing tensor to GPU
a = torch.rand(3,4)
a

tensor([[0.7761, 0.3679, 0.7098, 0.3447],
        [0.9248, 0.1358, 0.4633, 0.3991],
        [0.5746, 0.0227, 0.3411, 0.1238]])

In [9]:
b = a.to(device) #on GPU now

In [12]:
#Time comparison between CPU and GPU

size = 10000
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f'Time for CPU: {cpu_time:.4f} seconds')

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f'Time for GPU: {gpu_time:.4f} seconds')

print(f"Sepeedup (CPU/GPU): {cpu_time}/{gpu_time}")

Time for CPU: 24.5605 seconds
Time for GPU: 0.6932 seconds
Sepeedup (CPU/GPU): 24.560533046722412/0.6931815147399902


Reshaping Tensors

In [23]:
a = torch.rand(2,3,4)
a

tensor([[[0.9766, 0.2893, 0.1601, 0.0029],
         [0.7806, 0.2144, 0.1022, 0.1735],
         [0.0399, 0.7331, 0.9215, 0.2211]],

        [[0.2571, 0.0151, 0.1401, 0.9179],
         [0.0332, 0.2995, 0.0220, 0.5577],
         [0.0653, 0.7678, 0.8073, 0.6984]]])

In [27]:
a.reshape(3,2,4)

tensor([[[0.9766, 0.2893, 0.1601, 0.0029],
         [0.7806, 0.2144, 0.1022, 0.1735]],

        [[0.0399, 0.7331, 0.9215, 0.2211],
         [0.2571, 0.0151, 0.1401, 0.9179]],

        [[0.0332, 0.2995, 0.0220, 0.5577],
         [0.0653, 0.7678, 0.8073, 0.6984]]])

In [28]:
a.flatten() #will give 1D tensor

tensor([0.9766, 0.2893, 0.1601, 0.0029, 0.7806, 0.2144, 0.1022, 0.1735, 0.0399,
        0.7331, 0.9215, 0.2211, 0.2571, 0.0151, 0.1401, 0.9179, 0.0332, 0.2995,
        0.0220, 0.5577, 0.0653, 0.7678, 0.8073, 0.6984])

In [29]:
a.permute(2,0,1) #1st column(0) goes to 2nd place, 2nd(1) to 3rd and 3rd(2) to first place #order of column ko permuation kardo

tensor([[[0.9766, 0.7806, 0.0399],
         [0.2571, 0.0332, 0.0653]],

        [[0.2893, 0.2144, 0.7331],
         [0.0151, 0.2995, 0.7678]],

        [[0.1601, 0.1022, 0.9215],
         [0.1401, 0.0220, 0.8073]],

        [[0.0029, 0.1735, 0.2211],
         [0.9179, 0.5577, 0.6984]]])

In [31]:
c = torch.rand(226,226,3) #this is a standard image size and will be used multiple times 226,226,3
c

tensor([[[0.1635, 0.4097, 0.8884],
         [0.7153, 0.1342, 0.9061],
         [0.0359, 0.5933, 0.0880],
         ...,
         [0.9590, 0.1498, 0.4263],
         [0.2073, 0.1092, 0.1253],
         [0.8571, 0.8716, 0.7581]],

        [[0.4226, 0.6888, 0.3451],
         [0.4211, 0.9970, 0.0583],
         [0.5221, 0.1337, 0.2061],
         ...,
         [0.0633, 0.9824, 0.7740],
         [0.9931, 0.7037, 0.6902],
         [0.7806, 0.5040, 0.0404]],

        [[0.6332, 0.4470, 0.1711],
         [0.6509, 0.5789, 0.9047],
         [0.8326, 0.7410, 0.5115],
         ...,
         [0.6988, 0.4114, 0.6492],
         [0.3954, 0.0459, 0.9124],
         [0.2667, 0.8745, 0.9929]],

        ...,

        [[0.1337, 0.5638, 0.1734],
         [0.9960, 0.3538, 0.9562],
         [0.8158, 0.2564, 0.2846],
         ...,
         [0.3078, 0.9832, 0.9390],
         [0.6977, 0.9669, 0.6891],
         [0.6345, 0.7654, 0.7538]],

        [[0.9622, 0.7794, 0.4223],
         [0.2635, 0.1007, 0.2606],
         [0.

In [34]:
c.unsqueeze(0).shape #add new dimension at a given place 0,1,2,3...

torch.Size([1, 226, 226, 3])

In [39]:
d= torch.rand(1,20)
d.squeeze(0).shape #ulta here, wo us position ka dimension nikaal dega
#these will be used a lot

torch.Size([20])

In [40]:
import numpy as np

In [41]:
a = torch.tensor([1,2,3])
a

In [42]:
#convert to numpy array
b = a.numpy()
b

array([1, 2, 3])

In [44]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [45]:
d = torch.from_numpy(c) #convert numpy array to tensor
d

tensor([1, 2, 3])